spring.application.name=StaffHub
# application.properties
server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/StaffHub
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG


# 💣 DANGER: This drops and recreates your tables on EVERY restart!
# spring.jpa.hibernate.ddl-auto=create
