spring.application.name=StaffHub
# debug=true
# application.properties
server.port=${SERVER_PORT}

# 👇 DATABASE CONFIGURATION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 👇 JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=${HIBERNATE_LOG_LEVEL}
# spring.jpa.show-sql=true


# 💣 DANGER: This drops and recreates your tables on EVERY restart!
# spring.jpa.hibernate.ddl-auto=create

# Test Security details -- don't use in Production
spring.security.user.name=admin
spring.security.user.password=admin


# 👇 JWT SECRET
 jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}